root: true
env:
  browser: true
  node: true
  es6: true
  jest: true
  commonjs: true
parser: "@typescript-eslint/parser"
ecmaFeatures:
  jsx: true # 启用 JSX
  globalReturn: true # 允许在全局作用域使用 return 语句
plugins: 
  - "@typescript-eslint"
  - "react"
  - "import"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
settings:
  react:
    pragma: "createElement" # Pragma to use, default to "React"
parserOptions:
  sourceType: "module" 
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
    generators: true
    experimentalObjectRestSpread: true
  # 列举不需要检查的全局对象
globals:
  __weex_data__: true
  WXEnvironment: true
# "off"或者0    //关闭规则关闭
# "warn"或者1    //在打开的规则作为警告（不影响退出代码）
# "error"或者2    //把规则作为一个错误（退出代码触发时为1）
rules:
  semi:
    - 2
    - always
  quotes: [2, "double"] # 要求使用单引号
  indent: [2, "tab"] # 要求使用两个空格的缩进
  no-console: 0 # 禁止使用 console
  eqeqeq: 2 # 要求使用 === 和 !==